### ISSUE TITLE
Proposal. Use additional cli params to say that tables or columns renamed

### ISSUE THREAD

**Issue by Murmurianez** [MRVMV/sequelize-mig#106]
I don't know how it works under the hood but I think it is not so bad to use additional params until will be found better solution

For example:
`sequelize-mig migration:make -n <migration name> --rename-tables prevName1:newName1,prevName2:newName2`
`sequelize-mig migration:make -n <migration name> --rename-columns tableName::prevColumnName1:newColumnName1,tableName::prevColumnName2:newColumnName2`
and save info about renaming in _current.json

I think it's better than nothing

**Comment by MRVMV** [comment]
Hey!
sorry for being late... I have some exams and i will return to update this library after them zzzz
anyway thx for great suggestion :)
i was thinking about adding an auto detection of only capitalization and things like this and like adding table name to column name like personId and small things like this so i think i can add this one to that one too :)

anyway it will be much better if you can help me with a PR :)

**Comment by AllenAnthes** [comment]
@MRVMV Regarding auto detection I figure using Django's `generate_renamed_fields` function as a starting point could probably be helpful - https://github.com/django/django/blob/7cc6899d4176539e5d59a2e921b938904d3a8944/django/db/migrations/autodetector.py#L818-L854

If I get some time I might attempt throwing together a PR for it.

**Comment by MRVMV** [comment]
@AllenAnthes Yep thats interesting :)
I hope you can try with it. It will be great to merge!

**Comment by MRVMV** [comment]
#229 
and fixed last errors in #240

**Comment by MRVMV** [comment]
@Murmurianez do you think we should add any thing other than this?
credits to @AllenAnthes for his great Work!
