### ISSUE TITLE
[ERR_INVALID_FILE_URL_PATH]: File URL path must be absolute

### ISSUE THREAD

**Issue by Mixermachine** [MRVMV/sequelize-mig#139]
Hy there,

I just started to use your project and seem to have hit a roadblock.
I initialized my project with sequelize-cli and already got two migrations for two tables.
When I now try to run
`sequelize-mig migration:make -n add-deployment-releation-to-service`

I get 
```
_current.json not found. first time running this tool
File URL path must be absolute
```
_current.json is not created.

This is my folder structure.
![image](https://user-images.githubusercontent.com/1538187/103655592-c4fbe380-4f67-11eb-987a-96f678df54b1.png)
All commands are executed from the src folder.

Versions:
sequelize-mig: 2.5.0

sequelize: 6.3.5
sequelize-cli: 6.2.0

nodeJS: 15.5.0

I also tried sequelize-mig: 2.4.1 which produced the same error with a more verbose output (man page).

Greetings from Munich

Edit:
My project is private (Master thesis) but I can give you temporary access if that helps

**Comment by MRVMV** [comment]
@Mixermachine Hey :)
I tried in a lot of ways but didnt find anything broken...
anyway i pushed some commits which adds --log-level option and added a lot of checks for broken files or whatever so its easier to spot the problem 
anyway i cant merge them today until i try some more tomorrow 
if you can try the GitHub develop branch or wait a little :)

I hope we can spot the problem as quick as possible...
P.S. i hope i dont need to get into something private just let us try like this :)

**Comment by Mixermachine** [comment]
@MRVMV Hey, thanks a lot for your work.

No worries, I won't pull you into my project ^^

Do you know when you can do a release?
I'm currently building some other features of my project.
I will revisit this one tomorrow or the day after :)

Thanks again

Greetings from Munich

**Comment by MRVMV** [comment]
@Mixermachine Hey again!
If you can check right now and send me whatever you see in console
Greetings from Syria :)

**Comment by Mixermachine** [comment]
@MRVMV Hy to Syria :)
I have updated to 2.6.0.

I'm getting this:
```
sequelize-mig migration:make -n initial-migration
_current.json not found. first time running this tool
sequelize index file is not valid probably. solve it and try again: TypeError [ERR_INVALID_FILE_URL_PATH]: File URL path must be absolute
```

I have searched for the _current.json file but I have not found it :/

**Comment by MRVMV** [comment]
Then here sequelize-mig couldnt read index.js file for some reason... Can you check it?
Ignore the second line its not important it just indicate that it's your first time using the tool

**Comment by Mixermachine** [comment]
This is my index file
I have added a sanity check at startup but this should run without a problem.

Maybe it doesn't find the index file?
it's under src/models and i execute from the src folder.
```
'use strict';

const fs = require('fs');
const path = require('path');
const Sequelize = require('sequelize');
const basename = path.basename(__filename);
const env = process.env.NODE_ENV || 'development';
const config = require('../../config/db-config.json')[env];
const db = {};

let sequelize;
if (config.use_env_variable) {
  sequelize = new Sequelize(process.env[config.use_env_variable], config);
} else {
  sequelize = new Sequelize(config.database, config.username, config.password, config);
}

fs
    .readdirSync(__dirname)
    .filter(file => {
      return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js');
    })
    .forEach(file => {
        const model = require(path.join(__dirname, file))(sequelize, Sequelize.DataTypes);
        db[model.name] = model;
    });

Object.keys(db).forEach(modelName => {
    if (db[modelName].associate) {
        db[modelName].associate(db);
    }
});

console.info('DB sanity check')
Promise.all(Object.keys(db).map(modelName => {
    return db[modelName].findOne().catch(err => {
        console.error('Error when trying to check table ' + modelName + '. ', err)
        console.warn('*** Has the migration been executed? ***')
        process.exit(1);
    });
})).then(_ => console.info('DB is healthy'));

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;
```


There is a .sequelicerc file in the src folder
```
'use strict';

var path = require('path')

module.exports = {
  'config':          path.resolve('..', 'config', 'db-config.json'),
  'migrations-path': path.resolve('migrations'),
  'models-path':     path.resolve('models'),
  'seeders-path':    path.resolve('seeders'),
}
```

**Comment by MRVMV** [comment]
@Mixermachine sorry for the long delay but i think its fixed now please try it again

**Comment by Mixermachine** [comment]
@MRVMV No problem, thanks for your work :)
I will have a look at it

**Comment by Mixermachine** [comment]
@MRVMV Thanks a lot for the new version.
The _current.json file is now generated and the migration works 👍

**Comment by MRVMV** [comment]
@Mixermachine Thats nice!
