### ISSUE TITLE
defaultValue = null throws when running migration:make

### ISSUE THREAD

**Issue by flaviogragnolati** [MRVMV/sequelize-mig#185]
**Description**: Setting the value of `defaultValue` to `null` will throw: `Cannot read property 'constructor' of null`, when running sequelize-mig migration:make.

**To Reproduce**: Create a model and add a field that has a defaultValue=null, then run migration:make

**Expected behavior**: Run the migration

**Workaround**: Helper function getDefaultValueType, checks for object or function and proceeds accordingly, but when the `defaultValue=null` it will fall in object category, so when trying to read constructor will throw the error. I've added an if statement that explicitly checks for null, if so, return the value as is. I don't thinks that's a proper solution, is it???

**Comment by MRVMV** [comment]
Hey :)
Im really sorry because im busy and i couldnt find the problem easily and needs more searching and i dont have time zzz
i will be happy if you can try with it :)

**Comment by MRVMV** [comment]
trying to fix this in this pr #226
