### ISSUE TITLE
Model with field type array of strings doesn't work.

### ISSUE THREAD

**Issue by anujkumar14** [MRVMV/sequelize-mig#200]
One of the models in my application has data type as below.
**DataTypes.ARRAY(DataTypes.STRING)**

When i run '**sequelize-mig migration:sync**' , i am getting error as:
**sequelize index file is not valid probably. solve it and try again: TypeError: Cannot read property 'length' of null**

If I comment this field in the model and run , it works fine.

**Comment by anujkumar14** [comment]
Hi @MRVMV can you please check the PR.Thanks.
I am not able to use this library due to this issue.

**Comment by MRVMV** [comment]
@anujkumar14 done!
thanks for valuable contribution!
i just merged it
