### ISSUE TITLE
_current.json save location does not respect .sequelizerc

### ISSUE THREAD

**Issue by AllenAnthes** [MRVMV/sequelize-mig#213]
If a `.sequelizerc` file is present `modelsDir` is updated to the specified directory but `stateDir` remains at `./models`

https://github.com/MRVMV/sequelize-mig/blob/f650f9ae8ae20fa1f10dc87691c4c8a97d3213bd/lib/helpers.js#L195-L200

**Comment by MRVMV** [comment]
yep thats right just a second and I will add this one thats easy :)
