### ISSUE TITLE
Migrations doesn't run in transactions

### ISSUE THREAD

**Issue by Vardiak** [MRVMV/sequelize-mig#257]
There shouldn't be a `this` here.

https://github.com/MRVMV/sequelize-mig/blob/0cf8f3d2ae278f74a3db177350e3bc17ae88bf77/lib/assets/migrations/skeleton.js#L35

**Comment by MRVMV** [comment]
To be honest I don't remember this part and it's old one by the old developer 🙄
So if you know how to solve it i hope you make a PR

**Comment by Vardiak** [comment]
> To be honest I don't remember this part and it's old one by the old developer 🙄
> So if you know how to solve it i hope you make a PR

It's actually really easy to figure it out when reading the code. It must have been auto completed by an IDE since the exported module contains the `useTransaction` variable. On my side, it is always undefined in the function. Since it is declared in the file scope, it would make way more sense without `this`.

**Comment by MRVMV** [comment]
P. S again... I DONT HAVE A PC WITHIN MY HANDS IN THESE DAYS 😂
I'm just depending on remembering what are you talking about and not really opening the file to read what is written there 😂 and I'm reading issues from my mobile...
So surely open a PR and test it well too and I will be happy to merge it 😂

**Comment by MRVMV** [comment]
@Vardiak Are you up to make a PR?
