### ISSUE TITLE
Make migration has "DOUBLE PRECISION" resulting in Unexpected token, expected ","

### ISSUE THREAD

**Issue by knivore** [MRVMV/sequelize-mig#55]
Encountering SyntaxError: Unexpected token, expected "," when trying to make migration. Seems like there's "DOUBLE PRECISION" instead of DOUBLE

**Comment by MRVMV** [comment]
not enough info i didnt get the idea where does that happen and how?
send me some example of model making this problem @knivore

**Comment by knivore** [comment]
Apologies, have attached the model code below:

`/* jshint indent: 2 */

const Sequelize = require('sequelize');
module.exports = (sequelize, DataTypes) => {
  return Geolocation.init(sequelize, DataTypes);
}

class Geolocation extends Sequelize.Model {
  static init(sequelize, DataTypes) {
  super.init({
    geo_id: {
      autoIncrement: true,
      type: DataTypes.BIGINT,
      allowNull: false,
      primaryKey: true
    },
    latitude: {
      type: DataTypes.DOUBLE,
      allowNull: true
    },
    longitude: {
      type: DataTypes.DOUBLE,
      allowNull: true
    },
    created_date: {
      type: DataTypes.DATE,
      allowNull: false
    },
    created_by: {
      type: DataTypes.STRING(255),
      allowNull: false
    },
    updated_date: {
      type: DataTypes.DATE,
      allowNull: false
    },
    updated_by: {
      type: DataTypes.STRING(255),
      allowNull: false
    }
  }, {
    sequelize,
    tableName: 'geolocation',
    version: true,
    createdAt: 'created_date',
    updatedAt: 'updated_date'
    });
  return Geolocation;
  }
}
`

When I try to run the following command - "sequelize-mig migration:make -n initial" for the first time, I get the following in the terminal.

`
SyntaxError: Unexpected token, expected "," (114:40)
  112 |         "geolocation",{
  113 | "geo_id": { "type": Sequelize.BIGINT, "field":"geo_id", "primaryKey":true, "allowNull":false, "autoIncrement":true },
> 114 | "latitude": { "type": Sequelize.DOUBLE PRECISION, "field":"latitude", "allowNull":true },
      |                                        ^
  115 | "longitude": { "type": Sequelize.DOUBLE PRECISION, "field":"longitude", "allowNull":true },
  116 | "created_date": { "type": Sequelize.DATE, "field":"created_date", "allowNull":false },
  117 | "created_by": { "type": Sequelize.STRING(255), "field":"created_by", "allowNull":false },
`

**Comment by MRVMV** [comment]
@knivore ok ok got it and i think i knew where is the problem but i dont know how should we make a solution... I will check it

**Comment by MRVMV** [comment]
This should fi the problem #63 please try it so i can close this issue
